routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/admin', [AdminController::class, 'adminPage'])->name('admin.site');

Route::resource('/admin', AdminController::class)->only([
    'create', 'store', 'destroy',
]);;

Auth::routes();

Route::get('/cart', [CartController::class, 'cartList'])->name('cart.list');
Route::get('/historial-compras', [CartController::class, 'compras'])->name('cart.compras');
Route::get('/', [HomeController::class,'index']);
Route::get('/search', [HomeController::class,'searchBook'])->name('home.search');
Route::get('/{book}', [HomeController::class,'show'])->name('home.show');

Route::post('/cart', [CartController::class, 'addToCart'])->name('cart.store');
Route::post('/update-cart', [CartController::class, 'updateCart'])->name('cart.update');
Route::post('/remove-cart', [CartController::class, 'removeCart'])->name('cart.remove');
Route::post('/clear-cart', [CartController::class, 'clearAllCart'])->name('cart.clear');
Route::post('/cart-pay', [CartController::class, 'payBooks'])->name('cart.pay');

Route::resource('dashboard/book', BookController::class);
Route::post('dashboard/book/{shopping}/process',[BookController::class,'process'])->name('book.process');
Route::post('dashboard/book/{book}/picture', [BookController::class,'picture'])->name('book.picture');

resources/views/dashboard/_form.blade.php
@csrf

<div class="form-group">
    <label for="title">Titulo</label>
    <input class="form-control" type="text" name="title" id="title" value="{{ old('title',$book->title)}}">
    @error('title')
        <small class="text-danger">{{ $message}}</small>
    @enderror
</div>
<div class="form-group">
    <label for="url_clean">Autor</label>
    <input class="form-control" type="text" name="author" id="author" value="{{ old('author',$book->author)}}">
    @error('author')
        <small class="text-danger">{{ $message}}</small>
    @enderror
</div>

<div class="form-group">
    <label for="category_id">Categorias</label>
    <select class="form-control" name="category_id" id="category_id">
        @foreach ($categories as $title => $id)
            <option {{$book->category_id == $id ? 'selected="selected"' : ''}} value="{{$id}}">{{$title}}</option>
        @endforeach
    </select>
    @error('category_id')
        <small class="text-danger">{{ $message}}</small>
    @enderror
</div>

<input type="hidden" value="{{ $user }}" name="editorial">

<div class="form-group">
    <label for="url_clean">Precio</label>
    <input class="form-control" type="number" step="0.01" min="0" name="price" id="price" value="{{ old('price',$book->price)}}">
    @error('price')
        <small class="text-danger">{{ $message}}</small>
    @enderror
</div>

<div class="form-group">
    <label for="url_clean">Lenguaje</label>
    <input class="form-control" type="text" name="lenguage" id="lenguage" value="{{ old('lenguage',$book->lenguage)}}">
    @error('lenguage')
        <small class="text-danger">{{ $message}}</small>
    @enderror
</div>

<div class="form-group">
    <label for="content">Descripcion</label>
    <textarea class="form-control" name="description" id="description" row="3">{{ old('description',$book->description)}}</textarea>
    @error('description')
        <small class="text-danger">{{ $message}}</small>
    @enderror
</div>

<input type="submit" value="Enviar" class="btn btn-primary">

resources/views/dashboard/create.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Agregar Libro</h4>
    </div>
    <div class="card-body ml-5 mr-5 pr-5 pl-5">
        <form action="{{ route( "book.store" )}}" method="post">

            @include('dashboard._form')
        
        </form>
    </div>
@endsection

resources/views/dashboard/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Actualizar Libro con id: {{$book->id}}</h4>
    </div>
    <div class="card-body ml-5 mr-5 pr-5 pl-5">
        <form action="{{ route( "book.update",$book->id )}}" method="post">
            @method('put')
            @include('dashboard._form')
        </form>
    </div>

    <br>

    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Imagen de Libro</h4>
        </div>
        <div class="card-body">
            <form action="{{ route( "book.picture",$book->id )}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col">
                        <input type="file" name="picture" class="form-control">
                    </div>
                    <div class="col">
                        <input type="submit" class="btn btn-primary" value="Subir">
                    </div>
                </div>
            </form>
            <div class="row">
                <div class="col-3">
                    <img class="w-100" src={{"http://bookstore.test/". $book->picture}}>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <a class="btn btn-success mt-5" href="{{route("book.create")}}"> 
        Crear
    </a>
    <h3 class="mt-3">Libros de la Editorial {{$editorial}}</h3>
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Titulo</th>
            <th scope="col">Autor</th>
            <th scope="col">Price</th>
            <th scope="col">Creacion</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody>
            @foreach ($books as $item)
            <tr>
                <th scope="row">{{$item->id}}</th>
                <td>{{$item->title}}</td>
                <td>{{$item->author}}</td>
                <td>${{$item->price}}</td>
                <td>{{ Carbon\Carbon::parse($item->created_at)->format('Y-m-d') }}</td>
                <td>
                    <a href="{{ route('book.edit',$item->id) }}" class="btn btn-primary mb-1">
                        Editar
                    </a>
                    <button data-toggle="modal" data-target="#deleteModal" data-id="{{ $item->id }}" class="btn btn-danger mb-1">
                       Eliminar
                    </button>
                </td>
            </tr>
            @endforeach
        </tbody>
      </table>
      {{$books->links('pagination::bootstrap-4')}}
</div>

<div class="container">
  <h3 class="mt-3">Libros comprados</h3>
  <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Book</th>
          <th scope="col">Cantidad</th>
          <th scope="col">Estado</th>
          <th scope="col">Fecha</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
          @foreach ($shoppings as $item)
          <tr>
              <td scope="row">{{$item->book}}</td>
              <td>{{$item->quantity}}</td>
              <td>
                @if ($item->status == 0)
                  Comprado
                @elseif($item->status == 1)
                  En proceso de envio
                @else
                  Entregado
                @endif
              </td>
              <td>{{ Carbon\Carbon::parse($item->created_at)->format('Y-m-d') }}</td>
              <td>
                <form action="{{ route( "book.process",$item->id )}}" method="post">
                  @csrf
                  <input type="hidden" value="{{ $item->id }}" name="id">
                  <input type="hidden" value="{{ $item->status }}" name="status">
                  <button type="submit"
                    class="approved btn btn-{{ ($item->status == 0 ? "primary" : ($item->status == 1 ? "warning" : "success"))}}">
                      {{ ($item->status == 0 ? "Comprado" : ($item->status == 1 ? "En proceso" : "Entregado"))}}
                  </button>
                </form>
              </td>
          </tr>
          @endforeach
      </tbody>
    </table>
    {{$shoppings->links('pagination::bootstrap-4')}}
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="ModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <p>Estas seguro de eliminar el libro seleccionado?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

          <form id="formDelete" action="{{ route('book.destroy',0 )}}" data-action="{{ route('book.destroy',0 )}}" method="post">
            @method('delete')
            @csrf
            <button type="submit" class="btn btn-danger">Eliminar</button>
          </form>
        </div>
      </div>
    </div>
</div>

<script>
    window.onload = function(){
        $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget) // Button that triggered the modal
        var id = button.data('id') // Extract info from data-* attributes
    
        action = $('#formDelete').attr('data-action').slice(0,-1);
        
        $('#formDelete').attr('action',action + id)
        var modal = $(this)
        modal.find('.modal-title').text('Eliminar el libro con id: ' + id)
        });
    };
</script>
@endsection